-- MySQL Script generated by MySQL Workbench
-- sex 29 mai 2026 11:30:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_escola` ;
USE `banco_escola` ;

-- -----------------------------------------------------
-- Table `banco_escola`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `turma` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_escola`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `disciplina` VARCHAR(60) NOT NULL,
  `salario` DECIMAL(8,2) NOT NULL,
  `data_contratacao` DATE NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_professor`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_escola`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `carga_horaria` INT NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_curso_professor1_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_curso_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `banco_escola`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_escola`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `email` VARCHAR(120) NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_escola`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`matricula` (
  `id_aluno` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `data_matricula` TIMESTAMP NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_aluno`, `id_curso`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_aluno_has_curso_aluno_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_matricula_funcionario1_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_curso_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `banco_escola`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `banco_escola`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `banco_escola`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

